airbnb/synapse

Gemfile.lock
spec/lib/synapse/service_watcher_ec2tags_spec.rb
spec/spec_helper.rb
spec/support/configuration.rb
synapse.gemspec

Switches synapse to using the latest rspec. We are currently getting a ton of synapse warnings when running specs, and that should be on the TODO list to fix in a future PR.

Latest rspec

---

README.md
lib/synapse/haproxy.rb

This allows acls in frontend sections to reference backends without coupling
to the current convention of naming backends after watcher names
We're interested in doing farm failover at Yelp as described in http://blog.haproxy.com/2013/12/23/failover-and-worst-case-management-with-haproxy/ and I think all we need to do this is to have backup service watchers that have no port (so they'll get no frontend) and then have acls in the main service watchers that redirect to the backup backends if needed. However, to do this we need to know the names of backends and I'd rather not couple our configuration to something that synapse reserves the right to change.

Explicit watcher haproxy backend names

---

README.md
lib/synapse.rb
lib/synapse/file_output.rb
lib/synapse/haproxy.rb
lib/synapse/service_watcher.rb
lib/synapse/service_watcher/README.md
lib/synapse/service_watcher/base.rb
lib/synapse/service_watcher/dns.rb
lib/synapse/service_watcher/docker.rb
lib/synapse/service_watcher/ec2tag.rb
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/service_watcher/zookeeper_dns.rb
spec/lib/synapse/service_watcher_base_spec.rb
spec/lib/synapse/service_watcher_docker_spec.rb
spec/lib/synapse/service_watcher_ec2tags_spec.rb
spec/lib/synapse/service_watcher_spec.rb

Similar to what @bobtfish did in his nerve commit 258d62a823, this commit
allows Smartstack consumers to provide their own pluggable service
watchers.
Simply name your class correctly and put it in the right place and poof,
you have your own service watcher.

Allow pluggable watchers

---

lib/synapse/service_watcher/zookeeper.rb

Addresses incompatibility of per_callback threading in ZK, the way that
synapse calls unsubscribe within the callback, and ruby 2.X really not
liking joining on the current running thread.
Should fix #137 #99 and possibly #94 
I've tested this manually and events seem to get propagated ... I'd like to roll this out to a small portion of our infrastructure and see how it behaves.

Do not unregister the callback in the zk watcher

---

lib/synapse/service_watcher/ec2tag.rb
spec/lib/synapse/service_watcher_ec2tags_spec.rb

- don't require aws credential args, to allow using iam instance profiles
- fix bug where if an exception was raised in the watch method the sleep period got skipped. Better to wait the usual interval before retrying than to start running the failing discover instances method every few ms if something is wrong.

ec2tag watcher improvements

---

README.md

The previous installation directions are not great -- they are ambiguous
between whether synapse should be used as a library (and placed in the
depending app's Gemfile) vs being used as a standalone application (and
installed via `gem install`).
The best way I know to deploy a Ruby application is to use `gem install
--install-dir [path]` to install the application in that path. This
allows:
* the gem to be installed by any user, not just root
* the version of synapse's dependencies to be isolated from other system
gems
* easier redistribution as a system package
The downside is a relative large disk footprint - 36 MB as of writing.
Many files could be excluded from a system package, like the cache/
directory.

Update README.md with better installation directions

---

lib/synapse/haproxy.rb
lib/synapse/service_watcher/README.md
spec/lib/synapse/haproxy_spec.rb

This allows operators to declare that particular backends are backups, should have different failure modes (fall/rise), healthcheck rates, etc ... We need to add support to nerve to be able to pass these through, but this should help with #100.
If you want restarts to be forced when the state changes, you must use
the state file.

Allow arbitrary haproxy_server_options to be supplied to HAProxy.

---

Gemfile.lock
README.md
lib/synapse/service_watcher.rb
lib/synapse/service_watcher/marathon.rb
spec/lib/synapse/service_watcher_marathon_spec.rb
spec/spec_helper.rb
synapse.gemspec

I wrote this before I noticed #87, so in case you'd like a version that doesn't add a runtime dependency on `marathon_client` then this is your PR. Otherwise these are pretty much identical PRs and I'll close this out if you merge the other one.

Add marathon watcher

---

lib/synapse/file_output.rb
spec/lib/synapse/file_output_spec.rb
spec/lib/synapse/haproxy_spec.rb
spec/support/minimum.conf.yaml

It turns out that when removing services these files stick around
because synapse stops managing them, so in this patch we clean up
anything in the output directory that shouldn't be there.
Should fix #139
Also adds tests of the file output generator.

Cleanup old files that synapse no longer manages

---

lib/synapse/service_watcher/docker.rb
spec/lib/synapse/service_watcher_docker_spec.rb

This bit us when running one-off containers on our docker hosts (to run scripts, debug problems, etc.). Synapse would pick up the container because the image name and the private port matched, but the missing public port would cause it to generate an invalid haproxy config file and crash.
This fixes that by adding a simple check that the public port is present when deciding which containers to consider adding as backends.
It only does this for new-style port mappings because I can't find any docs on what the old-style port mappings looked like in this situation, nor is it clear that you could even prevent an exposed port from being mapped back when that version of the remote API was in use.

Filter out containers with unmapped ports

---

lib/synapse/service_watcher/zookeeper.rb

Adding support for aurora style service discovery.
Without patch:
```shell
[root@c90f0a9b92d9 /]# /usr/local/bin/synapse -c /etc/synapse/synapse.json
W, [2015-11-25T16:54:33.707037 #56]  WARN -- Synapse::ZookeeperWatcher: synapse: service hello_world: haproxy config does not include a port; only backend sections for the service will be created; you must move traffic there manually using configuration in `extra_sections`
I, [2015-11-25T16:54:33.707253 #56]  INFO -- Synapse::Synapse: synapse: starting...
I, [2015-11-25T16:54:33.707291 #56]  INFO -- Synapse::ZookeeperWatcher: synapse: starting ZK watcher hello_world @ hosts: 10.150.150.224:2181, path: /aurora/nobody/devel/hello_world
I, [2015-11-25T16:54:33.707315 #56]  INFO -- Synapse::ZookeeperWatcher: synapse: zookeeper watcher connecting …
```

add apache aurora service discovery support - issues/147

---

README.md
lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

Update lib/synapse/haproxy.rb to allow bind_address in the service haproxy section.   Allows bind address to be set per service and to override the global bind_address when needed.
My current use case is to configure services on local IPs ( myapi_brancha 127.0.0.2:443, myapi_anotherbranch 127.0.0.3:443 ) and then setup /etc/host entries to point to the services.   
```
...
"services": {
"myapi_brancha": {
...
"haproxy": {
"port": 443,
"bind_address": "127.0.0.2",
"myapi_anotherbranch": {
...
"haproxy": {
"port": 443,
"bind_address": "127.0.0.3",
```
```
127.0.0.2 myapi_brancha
127.0.0.3 myapi_anotherbranch
```
This allows front end applications using smartstack to access an api by name rather than port.   Will use this in a dev environment where there are multiple application servers each …

allow bind_address in the service haproxy section

---

README.md

Documenting this behavior could help other Synapse users.

Add a note about the state file's use for monitoring Synapse

---

lib/synapse/service_watcher/base.rb
lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_base_spec.rb

The high level context for this commit: we want to allow users to configure Synapse to distinguish different pools of service instances and to route traffic between them based on user configuration.
Original Discussion PR: https://github.com/airbnb/nerve/pull/81
Synapse's `discovery` configuration will support a new section `label_filter`. Let's assume the user is interested in setting up failover from the local availability zone to other nodes in the same region and eventually failing over to any available global instance.
```json
{ 
"example_service":  {
"haproxy": {
"backend_name": "example_service_default",
"frontend": [
"acl use_local_backend nbsrv(example_service_local) gt 2",
"acl use_regional_backend nbsrv(example_service_regional) gt 2",
"use_backend example_service_local …
```

Service watcher supports filtering backends by label 

---

README.md
lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

Currently we are doing shuffling (random ordering) only because we wanted to load
balance with round-robin to be more even across all machines.
This option allows one to specify how backends are ordered
in the final backend stanza configuration. This make it possible to support
usages that require an identical backend stanza configuration across machines.
@igor47  @jolynch  
cc @scarletmeow

Add `backend_order` option support to `haproxy`

---

lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

While testing the new release of synapse v0.13.0, I noticed that the zookeeper_dns discovery method was failing with the following error:
```
E, [2016-02-17T22:03:58.722362 #10392] ERROR -- 
Synapse::ServiceWatcher::ZookeeperDnsWatcher::Zookeeper: synapse: invalid data in ZK node 
example-service at /production/services/example-service/services: undefined method `call' for 
nil:NilClass
```
The root cause is that `@decode_method` is not properly initialized for the class, since it is initialized in `validate_discovery_opts` which is overwritten in ZookeeperDNSWatcher::Zookeeper. We can't call `super` since it's valid for the discovery method to be `zookeeper`.
There's probably a more elegant fix, let me think about it. The other issue is if we should yank v0.13.0 of synapse since it is …

zookeeper_dns is broken

---

spec/lib/synapse/file_output_spec.rb

Hi,
I have tried to fix a test which breaks on my system due to the order of files returned by glob.
I am running:
> Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
Ruby doc says that files order returned by glob is system dependent. It is problematic for just this test since this is the only one which return 2 elements.
It should be now fixed for all systems.
Regards.
Tony

Feat fix test failure on glob

---

lib/synapse/haproxy.rb

JSON used to raise an exception on an empty file, now it returns nil ...
Should fix #176

Fix regression where @seen becomes nil due to JSON parsing

---

README.md
lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

Hi, this PR replace : https://github.com/airbnb/synapse/pull/165
Sorry again.
Tony

Permit to hash servernames in affinity cookie

---

spec/support/minimum.conf.yaml

* 'services' is a hash, not a list
* 'services' needs a 'haproxy' key

Fix spec/support/minimum.conf.yaml

---

lib/synapse/service_watcher/dns.rb
lib/synapse/service_watcher/zookeeper_dns.rb

Extends `label_filter` functionality for `ZookeeperDnsWatcher`. This requires a change to `ZookeeperDnsWatcher` to forward the discovery options for label filtering and a change to `DnsWatcher` to pass a long any server `labels`.
Tested that label functionality is working for `ZookeeperDnsWatcher` with this patchset.
to: @SonicWang @igor47 @jolynch

label_filter support for zookeeper_dns

---

Gemfile.lock
lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb
spec/spec_helper.rb
synapse.gemspec

This PR contains no functional changes to Synapse. Instead, it adds a bunch of tests for the Haproxy class. We refactor the Haproxy class slightly to make testing easier. The main goal was to cover the state file handling with tests, since we're about to start using the state file at Airbnb. No bugs were found!
Ideally, we would only test the public methods of Haproxy -- `initialize`, `tick`, and `update_config`. however, if I set all of the other methods to private, we fail lots of existing tests, and testing the deep functionality of Haproxy via the public interface seems very tedious. So, although I intended to make that change here, I decided to save it for some other time.
to: @jolynch @scarletmeow

Haproxy tests

---

Gemfile.lock

Synapse version in Gemfile.lock needs to get bumped. My guess is this is some kind of interaction with Travis and `--deployment` being enabled because we have a Gemfile.lock in the repository. Anything other than the current version will trigger an error similar to `Could not find synapse-0.13.2 in any of the sources`
to: @igor47

Bump Gemfile.lock to fix specs

---

lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

This is needed because we are sorting backends using constructed
full string names. Currently we put `host:port` in front of `name`.
`host` could be an `ip` and in this case controlling ordering is hard.
Test: unit tests.
@scarletmeow @igor47 @jolynch

[haproxy] Put backend['name'] first in constructing backend name

---

lib/synapse/haproxy.rb

HAProxy closes its connection to the socket as soon as it finishes writing. This PR explicitly closes the socket from the synapse side. Without an explicit close, cleanup done on object finalization during garbage collection. This can cause synapse to temporarily accumulate a large number of socket file descriptors.
On a synthetic test with a large number of backends, this patch reduces the maximum number of open file descriptors from 940 to 52.
There are minor logging changes associated with this patch:
* added logging of error if an exception is raised when closing the file.
* if reading from the socket fails when called from https://github.com/airbnb/synapse/compare/master...brianwolfe:wolfe-socket-fd-cleanup?expand=1#diff-b2f6400f899968d5a5084ee66bf90b21R1106, there will be 2 error …

Clean up HAProxy sockets after reading

---

README.md
lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

we are running into haproxy CPU bottlenecks on some boxes. to get around those, we would like to run haproxy on multiple CPUs via `nbproc`. this PR enables the simplest way to configure `nbproc`, where all backends are listening on all processes and share the load. here is an example synapse config snapshot which would result in the desired behavior:
```json
{
"haproxy": {
"socket_file_path": [
"/var/haproxy/stats1.sock",
"/var/haproxy/stats2.sock",
],
"global": [
"nbproc 2",
"cpu-map 1 0",
"stats socket /var/haproxy/stats1.sock group smartstack mode 660 level admin process 1",
"cpu-map 2 1",
"stats socket /var/haproxy/stats2.sock group smartstack mode 660 level admin process 2",
```
this creates two independent haproxy processes, each with their own socket. we also tell synapse that two …

Multiple stats sockets

---

Gemfile.lock
README.md
lib/synapse/service_watcher/base.rb
spec/factories/backend.rb
spec/lib/synapse/service_watcher_base_spec.rb
spec/spec_helper.rb
synapse.gemspec

In this PR, we make the following changes:
* go from `label_filter` to `label_filters` -- this allows us to define multiple filters, which must ALL match
* add a new filter condition, for `not-equals`
* allow leader election to operate on filtered backends, thus making leader election and filters no longer mutually exclusive (the mutual exclusivity was not documented)
this covers our main use case -- utilize only backends in the current region and the current az (the default case), or utilize only backends in the current region and NOT the current az (in case of AZ failover).
as well, we refactor the specs for labels to use a factory to create the labels, vs creating hashes manually and being forced to specify a bunch of attributes we don't care about.
to: @jolynch @scarletmeow @nwadams …

Refactor label filter

---

README.md
config/synapse.conf.json
lib/synapse/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

This PR adds an additional parameter to support the ssl configuration in haproxy. As specified in test and example config, those options could be: {ssl, crt, ciphers, accept-proxy, ca-file etc.}

Adding additional bind_options param to support ssl configuration

---

README.md

* The sample configuration file provided under the section `HAProxy shared HTTP Frontend` is not a valid YAML file because of a missing quotation mark. This patch adds the missing quotation mark so that the configuration is usable as it is.

Add Missing Quotation Mark in the Sample Config

---

lib/synapse/config_generator/haproxy.rb
lib/synapse/service_watcher/base.rb
spec/lib/synapse/haproxy_spec.rb

Two things here.
First, we toggle ```updated``` on a service watcher from its ```set_backends``` method if we detect a diff in backends.
Second, in haproxy generator, in ```generate_config``` method we use cached frontend and backend stanzas unless a given watcher has ```updated``` set to true.
cc @jolynch

cache haproxy stanzas in generate_config

---

lib/synapse/config_generator/README.md
lib/synapse/config_generator/file_output.rb
spec/lib/synapse/file_output_spec.rb

This uses the revision machinery to not have to JSON.load all the files every update.

Do less work on file output updates

---

Gemfile.lock
lib/synapse/config_generator/file_output.rb
lib/synapse/version.rb
spec/lib/synapse/file_output_spec.rb

@solarkennedy I think this should allow us to prevent the nginx_listeners from showing up in files (I have to disable in synapse-tools, but machinery is there now).

Allow disabled files

---

README.md
lib/synapse/config_generator/haproxy.rb
spec/lib/synapse/haproxy_spec.rb
spec/support/minimum.conf.yaml

This way we still get different orders on different client machines,
preventing long lived connections from all hitting the first or second
server, but also for reloads we get a consistent ordering that does not
invalidate the HAProxy state file (which assumes your backends don't
change order).

Make shuffle reproducible

---

lib/synapse/config_generator/haproxy.rb

The .max was already a linear scan ... I feel like this is just easier to reason about (less likely to have strange bugs where we wrap around and something doesn't go to plan).

To find the next server id, just count up

---

.travis.yml

THis is a test to see if it fixes the 1.9 issue.

Try upgrading bundler on travis

---

lib/synapse/config_generator/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

to: @jolynch 
A bug was introduced into the generate_Backend_stanza. @state_cache.backends is expecting watcher.name as the input argument, but it got the watcher object.
With the bug, when Synapse generates the haproxy config, it only sees the "enabled" services as reported by the watchers, but does not see all known backends in the state cache (because search by 'watch', instead of watcher.name, in the state cache failed silently). This increases number of haproxy restarts when Synapse is restarted. 
Pass the correct argument to @state_cache.backends
Added rspec test to cover this bug.

[synapse] fix bug in generate_backend_stanze

---

bin/synapse
spec/bin/synapse_spec.rb
spec/support/configuration.rb
spec/support/minimum.conf.yaml

Allows for string interpolation and other Ruby syntax in config files. Useful to dynamically build services based on local environment.

Support embedded ruby (ERB) in config files

---

README.md
lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

This PR adds a `generator_config_path` option that can be used to determine where the zookeeper discovery method will look in zookeeper for the generator config.    This PR also adds a "disabled" option to prevent generator configs from being read from zookeeper.
Prior to this patch, the `path` option is used, and if the `path` node in zookeeper has data, that data always overrides any other generator config.
However, there are cases where you want to have multiple generator configs that share the same instances; for example, for az-aware routing.      In order to safely roll out this feature, you may also swant to disable the zookeeper-based loading of generator config information.
For az-aware routing, you might implement this with two smartstack services, as follows:
```
"services": { …
```

add generator_config_path config option

---

lib/synapse/config_generator/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

If a user pushes a configuration with an `haproxy_server_options` value that is not a string, it will cause the service_watcher and Synapse to exit because of a NoSuchMethod Exception when `split()` is called.
This adds type validation on the value of the `haproxy_server_options` and `server_options` when a String is expected.

added type validation for haproxy_server_options

---

lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Summary
This PR makes synapse watcher to keep alive as long as the session has not expired. The change avoids unnecessary Synapse restart when there is only short network disconnection between watcher and the zk cluster.
Reviewers
@darnaut @alexism

[Synapse] fix synapse panic in short disconnection

---

Gemfile.lock
config/synapse.conf.json
lib/synapse.rb
lib/synapse/config_generator/haproxy.rb
lib/synapse/service_watcher/base.rb
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/statsd.rb
lib/synapse/version.rb
spec/lib/synapse/haproxy_spec.rb
synapse.gemspec

Adding support for exporting metrics through `statsd`.
Also, exporting basic metrics about `synapse`'s health and performance.
How it was tested:
unit tests + manual run and checking exported metrics
Reviewers: @lap1817 @alexism

Adding `statsd` dependency and exporting some stats

---

lib/synapse.rb

While monitoring Synapse using the newly exported metrics we realized
there's not enough information about the reported failures to help
investigations. Adding exception name and message to the failure metrics
should provide a big help with that.
Reviewers: @lap1817 @ken-experiment

adding exception info to exported metrics

---

Gemfile.lock
lib/synapse/service_watcher/dns.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_dns_spec.rb

Allow the the `dns` and `zookeeper_dns` service discovery methods to handle service nodes with an IP address for the `host` field.
This facilities migrating services from other discovery methods (such as `zookeeper`) to the `dns` (or `zookeeper_dns`) method by allowing the service discovery method to be changed before publishing new service nodes with hostnames.

Allow DNS discovery to handle service nodes with an IP address for host

---

Gemfile.lock
README.md
lib/synapse/config_generator/haproxy.rb
lib/synapse/version.rb
spec/lib/synapse/haproxy_spec.rb

Add support for some basic template interpolation in the `server_options` field. The name, host, and port of a particular backend server are made available for insertion into a `server_options` block, so that a server options configuration can be supplied to synapse that will vary based on the details of a host being configured. This allows options to be set that are dependent on information coming from the service discovery backend.
In particular, this allows one to disable TLS health checks for a TLS backend by specifying `check port <portnumber>`, where `portnumber` varies depending on the backend port that has been discovered by your discovery system.
@lap1817 @juchem @Jason-Jian

Support basic templating in server options

---

lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Currently, if `generator_config_path` is pointed to a non-existent zk node, synapse will crash.
Let's fail more gracefully and use the default behavior of `new_config_for_generator = {}`.
@bsherrod @reissbaker 
cc @juchem @lap1817 (common contributors)

do not fail for no generator-config-path zk node

---

Gemfile.lock
lib/synapse/config_generator/file_output.rb
lib/synapse/version.rb
spec/lib/synapse/file_output_spec.rb

Problem: synapse work if the config is `{"haproxy" => {..}, "file_output"=>{}}`
synapse crashes if config is `{"haproxy" => {..}}`
and does not contain `file_output`
Solution: Test for nil?
Tests: Added test case. Tested on a service.

Do not crash if file_output not present

---

.travis.yml
Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb

When parsing an unknown `generator` from service configuration stored on `zookeeper`, `synapse` skips it but still throw `error`. `zookeeper` is designed as a generic datastore for service discovery data but not only for synapse. Therefore, there might be any random key-value pair stored under `zookeeper` node, instead of those known by synapse. This is expected and reasonable. Instead of logging as `error` level, it should make more sense to just be a `warn`.
Also, I have to limit `travis` script to use `bundler 1.17.3` in order to support legacy ruby version.
```
ERROR:  Error installing bundler:
The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
bundler requires Ruby version >= 2.3.0. The current ruby …
```

warn when parsing a unknown generator name

---

lib/synapse.rb

config_generator.update_config has several steps are subjected to failure:
1. read existing config file
2. generate new config
3. write temp config file
4. replace existing config file
we need catch exception on this code path, emit success & failure counter, and log exception details
@austin-zhu @Jason-Jian @ken-experiment

Add failure counters for updating config

---

lib/synapse/config_generator/haproxy.rb

haproxy restart can potentially fail and need a failure counter for monitoring purpose
@austin-zhu @ken-experiment @Jason-Jian

Add failure counter for haproxy reload

---

lib/synapse/service_watcher/zookeeper.rb

Add failure counters metrics for zookeeper:
1. register watcher failure
2. get data failure
3. deserialize data failure
@austin-zhu @ken-experiment @Jason-Jian

Add failure counters for zookeeper watcher

---

lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

zookeeper get can return nil or throw timeout exception, when network is flaky or zookeeper is overloaded.
adding retry logics (by default 3 times with 5 second interval) can alleviate the problem.
if all retries failed, throw runtime error forcing the process to re-establish zookeeper connections.
@austin-zhu @ken-experiment

Add retry logics for zookeeper get

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb

we recently discover synapse 'stuck' issue in production: during zookeeper server reboot, watcher was lost forever for one zookeeper path
The key takeways are here:
1. zookeeper watcher is one-time trigger, if one watcher is lost and not re-set, any future events associated will not be notified.
2. zookeeper watcher setting involves two steps: 1. register watcher if it doesn't exist, 2 enable watcher by get/children call (with :watch = true)
2. during zookeeper server restart, client can potentially enter two states: session expire or reconnecting, the currently implementation doesn't handle reconnecting.
3. watcher can get lost when client is disconnected from server.
The fix is to listen on reconnect state, and then re-register and re-enable watcher.
Also log entry when watchers are …

Fix synapse watch lost during zookeeper server reboot

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb

due to zk-client implementation, it keeps a single thread open after registering the callback in order to guarantee high concurrency https://github.com/zk-ruby/zk/wiki/EventDeliveryModel
we need keep number of callback per watch as few as possible.
@austin-zhu @Jason-Jian

Remove on_connecting for less threads

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

When large service deploys, services  depending on this large service is constantly reloading zookeeper get on leaf nodes.
Unmodified:  During 1000 node service deploy, a single dependent service refreshed 7 times(7000 ZK.GET) in 2 minutes. 
```
ramya_krishnan@i-05bae5ca90fc95bb4:/etc/service/synapse/log testbox-14-production $ grep 06:47 current |grep discovered|grep monorail
I, [2019-05-31T06:47:13.992250 #20084]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered XXXX backends for service monorail
I, [2019-05-31T06:47:26.743540 #20084]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered XXXX backends for service monorail
I, [2019-05-31T06:47:41.702985 #20084]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered XXXX backends …
```

Throttle discover in zookeeper service watcher

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb

We discovered zk client bug that could potentially cause watcher refresh storm and zk overload, when zk server restart
while we are waiting for the fix to get reviewed and well tested:
https://github.com/airbnb/synapse/pull/292
For now remove on_connected callback to be safe
@Jason-Jian @allenlsy @Ramyak

Remove on_connected to avoid reconnect storm

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

If we get an event, do not sleep (discovery_jitter seconds)
```
Previous discovery
I, [2019-06-14T01:17:54.553668 #18252]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered 3 backends for service sssp-test
I, [2019-06-14T01:17:54.579559 #18252]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered 3 backends for service sssp-test-regional
I, [2019-06-14T01:17:54.592510 #18252]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered 3 backends for service sssp-test-local-az
15 seconds no activity. Then discovery without sleep
I, [2019-06-14T01:18:30.594380 #18252]  INFO -- Synapse::ServiceWatcher::ZookeeperWatcher: synapse: discovered 2 backends for service sssp-test-regional
I, [2019-06-14T01:18:30.595322 #18252]  INFO -- …
```

Avoid discovery_jitter sleep on first event

---

.travis.yml
Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

The on_connected callback was originally introduced to handle an issue that zookeeper session got stuck (will not receive zookeeper watch event forever), during a connection lost and reconnect.
But we discovered some side-effect of this fix, there are multiple on_connected callback get triggered for a single disconnect and reconnect (here seems other people are facing the same issue: https://github.com/zk-ruby/zk-eventmachine/issues/2). And since we do reset zookeeper watcher by read everything. This creates substantial load on zookeeper.
Here are two optimizations introduced by this change:
1. ensure there is only one watcher refresh within a time window (e.g. 60 seconds) no matter how many on_connected callback gets triggered
2. optimize the watcher refresh by just re-enable (parent and …

Improve on_connected callback to avoid reconnect storm

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Zookeeper sends `connected` notification to all clients after leader election, when it recovers from quorum loss.
The reads (to re-enable watcher) triggered by on_connected from single every client, become overwhelming for zookeeper
Until we can enable readonly mode (https://wiki.apache.org/hadoop/ZooKeeper/GSoCReadOnlyMode), we have to reduce the amount of read.
@Jason-Jian @austin-zhu @Ramyak

Remove on_connected callback to avoid read storm after leader election

---

.travis.yml
lib/synapse.rb

For load testing purpose
1. add option load_test_concurrency to launch multiple service watchers
Test with local zookeeper and test config:
```
{
"services": {
"mango-test": {
"discovery": {
"method": "zookeeper",
"generator_config_path": "disabled",
"use_path_encoding": true,
"path": "/mango-test/services",
"hosts": [
"127.0.0.1:2181",
],
"label_filter": {
"label": "az",
"value": "<%= ENV['AWS_AZ'] %>",
"condition": "equals"
}
},
"haproxy": {
"server_options": "check port %{port} inter 30s downinter 1s rise 1 fall 2 ssl verify required ca-file /etc/internal_x509/securestack_ca_chain.pem crt /etc/internal_x509/securestack_client_private_bundle.pem",
"listen": [
"mode http",
"option tcp-check",
"option httplog"
],
"backend": [
"option http-server-close"
],
"frontend": [
"acl …
```

Add option for load testing

---

Gemfile.lock
lib/synapse/service_watcher/base.rb
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/statsd.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

1. decode zk child name with base64 encoding to get ip, port, labels etc.
2. ensure backward compatibility: synapse with path encoding enabled works with old version of nerve safely
3. use variable length decoding to make schema more flexible:
a. prefix is optional encoded json
b. suffix is optional sequence number 
4. make decoding more producer driven
a. feature is enabled based on child name prefixed with protocol name `base64_`
b. json content is decided by producer encoding, no fields picking
The counterpart nerve change:
https://github.com/airbnb/nerve/pull/114
test synapse log:
```
{
"services": {
"mango-test": {
"discovery": {
"method": "zookeeper",
"generator_config_path": "disabled",
"use_path_encoding": true,
"path": "/mango-test/services",
"hosts": [
"127.0.0.1:2181",
], …
```

Add path encoding optimization

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

During path encoding optimization rollout, we found synapse reloads haproxy more often even when list of backends did NOT change. 
Synapse caches (in memory) the list of backends discovered last time and does a comparison against the list of backends newly discovered, and reload haproxy if there is a `change`. Before path encoding, the backend info include all fields even if they are nil, for example it could have `haproxy_server_options => nil`. After path encoding, the nil fields are not included, so `haproxy_server_options => nil` does not exist. This creates a false positive signal for haproxy reload, even though backends list and info do NOT change at all.
Keep schema fixed, so all fields of backend info are kept and compared disregarding they are nil or not. This is to alleviate …

Make schema fixed for backend info

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Synapse tries to create one znode per service path without checking its existence, this causes unnecessary zookeeper write and additional (error) transaction bump
The service path creation is already covered by the write side in status reporter like nerve:
https://github.com/airbnb/nerve/blob/f85ce262036a8233676a5b182449a777056da0df/lib/nerve/reporter/zookeeper.rb#L158
Synapse should be readonly, and it should not try to create service path. if the service path does not exist, it means the server side is not ready for discovery
Replace service path `creation` with `existence check`, and skip registering watch if service path does not exist.
Before the fix:
```
10/4/19 1:57:20 PM PDT session 0x100055c9085002a cxid 0x0 zxid 0xaa createSession 20001
10/4/19 1:57:20 PM PDT session …
```

Avoid creating parent path per zk session

---

Gemfile.lock
lib/synapse.rb
lib/synapse/version.rb

This adds metrics about the Synapse version per-ping. Tested by checking that metrics are properly emitted on a specific host.

Emit version with ping metric

---

Gemfile.lock
README.md
config/synapse.conf.json
lib/synapse/config_generator/haproxy.rb
lib/synapse/version.rb
spec/lib/synapse/haproxy_spec.rb

This PR adds the following:
* capability for Synapse to run a custom command to validate HAProxy config prior to writing the config file (config is held in a "staging" file before that)
- *Note:* this does not affect reloading, just writing the config. HAProxy will still get restarted, but it will continue to use good config.
- The goal is that the "production" config file (i.e. that used by the `HAProxy` process) will always be valid.
* configuration for HAProxy validation
* unit tests for those additions
Because of state file caching, it is still possible that certain bad state will remain in Synapse (in-memory and in cache file). However, that state will not propagate to HAProxy; HAProxy will remain with the last good state.
Synapse does not write bad HAProxy config:
```
I, …
```

Validate HAProxy config prior to writing config file

---

lib/synapse/config_generator/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

Currently, Synapse already crashes when all the required haproxy check parameters (`do_checks`, `candidate_config_file_path`, and `check_command`) are not set together. However, this crash does not have any meaningful information.
This PR validates that the configuration is all set together and if not, raises an error with a useful message (similar to other config checks already performed).
`candidate_config_file_path` missing:
```
$ RUBYLIB=lib bin/synapse -c ~/test-config/synapse/synapse-haproxy-validation.json
I, [2020-01-24T11:04:22.339294 #48364]  INFO -- Module: synapse: configuring statsd on host 'localhost' port 8125
/.../synapse/lib/synapse/config_generator/haproxy.rb:829:in `block (2 levels) in initialize': the `candidate_config_file_path` option is required when `do_checks` is …
```

Ensure that haproxy check parameters are set together

---

Gemfile.lock
spec/spec_helper.rb
synapse.gemspec

This change adds simplecov and simplecov-json to report code coverage.
To get code coverage information in your build you need to set the
CODE_COVERAGE env var to "true"
@panchr

Add simplecov and simplecov-json

---

lib/synapse.rb
lib/synapse/service_watcher.rb
lib/synapse/service_watcher/base.rb
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/service_watcher/zookeeper_dns.rb
spec/lib/synapse/service_watcher_base_spec.rb
spec/lib/synapse/service_watcher_dns_spec.rb
spec/lib/synapse/service_watcher_docker_spec.rb
spec/lib/synapse/service_watcher_ec2tags_spec.rb
spec/lib/synapse/service_watcher_marathon_spec.rb
spec/lib/synapse/service_watcher_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb
spec/lib/synapse_spec.rb

This PR allows for configuring a custom notification callback when a watcher has an update, instead of always called `synapse.reconfigure!` by default.
Note that the `BaseWatcher.reconfigure!` method essentially acts as a notification of an update: this triggers the main Synapse object to update the config generators (i.e. create new HAProxy configuration and reload the process).
This will be used as part of the multi-watcher (WIP: https://github.com/airbnb/synapse/pull/309), in order to allow the multi-watcher to receive notifications instead of the Synapse object. The multi-watcher will then notify Synapse directly, *after resolving the different child watchers.*  
@bsherrod @austin-zhu

Allow for configurable notification callback for watchers

---

lib/synapse/service_watcher/multi/multi.rb
lib/synapse/service_watcher/multi/resolver.rb
lib/synapse/service_watcher/multi/resolver/README.md
lib/synapse/service_watcher/multi/resolver/base.rb
spec/lib/synapse/multi_resolver/base_spec.rb
spec/lib/synapse/multi_resolver/loader_spec.rb
spec/lib/synapse/service_watcher_multi_spec.rb

_This PR is stacked on top of #311._
A `Resolver` is responsible for providing the abstraction that multiple watchers are one: it decides how to merge the list of `backends` from each one. This PRs adds:
* the interface for the `Resolver`
* a base implementation
* documentation on how to create new `Resolver`s
* `MultiWatcher` loads the resolvers
@bsherrod @austin-zhu

Add resolver interface and base implementation [stacked on #311]

---

README.md
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/service_watcher/zookeeper_poll.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

_This PR is stacked on top of #315._
Implement the `ZookeeperPollWatcher` watcher type, which uses long-polling instead of Zookeeper watches. The polling interval can be configured. The polling runs in a background thread that is interruptible.
```
I, [2020-03-06T15:39:36.212292 #20523]  INFO -- Module: synapse: configuring statsd on host 'localhost' port 8125
I, [2020-03-06T15:39:36.269757 #20523]  INFO -- Synapse::Synapse: synapse: starting...
...
I, [2020-03-06T15:39:36.275504 #20523]  INFO -- Synapse::ServiceWatcher::ZookeeperPollWatcher: synapse: zookeeper polling thread started
I, [2020-03-06T15:39:36.275572 #20523]  INFO -- Synapse::ServiceWatcher::ZookeeperPollWatcher: synapse: zookeeper polling discover called
...
I, [2020-03-06T15:39:36.276002 #20523]  INFO -- …
```

Implement ZookeeperPollWatcher

---

README.md
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/service_watcher/zookeeper_poll.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Refactoring out some common code in order to support a separate `ZookeeperPollWatcher` after.
The common code includes:
* Setup/teardown of Zookeeper connections
* Reading child data (path-encoding support / fallback)
`ZookeeperPollWatcher` will be approximately:
```ruby
class ZookeeperPollWatcher < ZookeeperWatcher
def start
@stop_watcher = false
@thread = nil
zk_connect do
@thread = Thread.new {
until @stop_watcher
discover
sleep some_time
end
}
end
end
def stop do
@stop_watcher = true
zk_teardown do
@thread.stop unless @thread.nil?
end
end
def discover
zk_children = @zk.children(path)
zk_children.each do |id|
backend = read_child_data(id)
new_backends << backend unless backend.nil?
end
new_config_for_generator = read_config_for_generator
set_backends(new_backends, …
```

Refactor Zookeeper watcher to support polling in future

---

lib/synapse.rb
lib/synapse/service_watcher/multi/multi.rb
lib/synapse/service_watcher/multi/resolver/README.md
lib/synapse/service_watcher/multi/resolver/base.rb
lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb

Implement the S3 toggle resolver, which periodically polls an S3 file for a map of `watcher name --> weight`. This map is used to randomly pick a watcher to use.
```
I, [2020-03-12T12:34:41.783884 #74406]  INFO -- Synapse::ServiceWatcher::Resolver::S3ToggleResolver: synapse: s3 toggle resolver: read s3 file: {"primary"=>100, "secondary"=>0}
I, [2020-03-12T12:34:41.783950 #74406]  INFO -- Synapse::ServiceWatcher::Resolver::S3ToggleResolver: synapse: s3 toggle resolver: chose watcher primary
I, [2020-03-12T12:34:51.857979 #74406]  INFO -- Synapse::ServiceWatcher::Resolver::S3ToggleResolver: synapse: s3 toggle resolver: read s3 file: {"primary"=>100, "secondary"=>0}
I, [2020-03-12T12:34:51.858024 #74406]  INFO -- Synapse::ServiceWatcher::Resolver::S3ToggleResolver: synapse: s3 toggle …
```

Implement S3 toggle resolver

---

lib/synapse/service_watcher/multi/multi.rb
lib/synapse/service_watcher/multi/resolver.rb
lib/synapse/service_watcher/multi/resolver/README.md
lib/synapse/service_watcher/multi/resolver/base.rb
lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
spec/lib/synapse/multi_resolver/base_spec.rb
spec/lib/synapse/multi_resolver/loader_spec.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb
spec/lib/synapse/service_watcher_multi_spec.rb

A `resolver` can independently trigger a change of the backends. For example, the new `S3ToggleResolver` can result in a new set of backends if the S3 file changes. That is, say we have two watchers with the following backends:
* A --> `[host_1, host_2]`
* B --> `[host_3, host_4]`
Say in S3, the toggle file originally says to only take backends from `A`. Then, that file changes to only take backends from `B`. `S3ToggleResolver` will notice this change, and change its reported backends to `[host_3, host_4]`.
Before this PR, those changes were not reflected because the underlying watchers themselves had not changed their backends. That is, neither watcher `A` nor watcher `B`'s backends changed. Instead, what changed is *how* we resolve the backends between the two. 
In order for that change …

Allow resolver to send notifications to MultiWatcher

---

lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
spec/lib/synapse/haproxy_spec.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb

Currently, the `S3ToggleResolver` will read the provided S3 file for every multi-watcher created. When a single Synapse has N watchers, the file will be read N times periodically. This creates unnecessary load.
This PR abstracts the S3 file reading into a separate `BackgroundS3Poller` class which performs the function of reading an S3 file, validating it, and deterministically picking a watcher. That watcher is shared by any `MultiWatcher` which uses that file.
Different `MultiWatcher` still have the flexibility of reading different S3 files; the `BackgroundS3Poller` will automatically manage this.
```bash
$ grep "read s3" test.out
I, [2020-03-25T13:13:14.954019 #19280]  INFO -- Synapse::ServiceWatcher::Resolver::S3ToggleResolver::BackgroundS3Poller: synapse: s3 toggle resolver: read s3 …
```

De-duplicate S3 file reads

---

lib/synapse/service_watcher/multi/multi.rb
lib/synapse/service_watcher/multi/resolver/README.md
lib/synapse/service_watcher/multi/resolver/base.rb
lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
spec/lib/synapse/multi_resolver/base_spec.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb
spec/lib/synapse/service_watcher_multi_spec.rb

The `MultiWatcher` resolvers only work on the backends currently. This ensures that service-level config is also considered.
Even though service-level config is set in Zookeeper, it does not appear in the generated HAProxy config.
```bash
$ zookeepercli -servers localhost:2181 -c get /services/service1 {"haproxy":{"server_options":"check port %{port} inter 30s downinter 1s rise 1 fall 2 ssl verify required ca-file ... ...","listen":["mode http","option tcp-check","cookie SRVID insert indirect nocache","option httplog"],"port":6009,"backend":["option http-server-close"],"frontend":["bind ::1:6009"]}}
$ cat haproxy.cfg
...
frontend service1
mode http
bind localhost:3213 ssl no-sslv3 crt /path/to/cert/example.pem ciphers ECDHE-ECDSA-CHACHA20-POLY1305
default_backend service1
backend service1 …
```

Resolve service-level configuration in MultiWatcher

---

lib/synapse.rb
lib/synapse/atomic.rb
lib/synapse/service_watcher/base/base.rb
lib/synapse/service_watcher/multi/multi.rb
lib/synapse/service_watcher/multi/resolver/README.md
lib/synapse/service_watcher/multi/resolver/base.rb
lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
lib/synapse/service_watcher/zookeeper/zookeeper.rb
lib/synapse/service_watcher/zookeeper_poll/zookeeper_poll.rb
spec/lib/synapse/atomic_spec.rb
spec/lib/synapse/multi_resolver/base_spec.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb
spec/lib/synapse/service_watcher_multi_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

The new ZookeeperPoll watcher runs in a background thread and needs to communicate with the main thread (in order to tell it when to update). Currently, it just calls a callback which will execute in the background thread, and that has some thread safety concerns.
Also, the main thread will read the state of each watcher. The fixes for this are:
1. Hold a Synapse-level lock when reconfiguring.
2. Hold a watcher-level lock when getting/setting any watcher state.
In addition, it runs the primary Zookeeper watcher in a background thread. This allows retry logic to *not* block the main thread.
```bash
$ grep server haproxy.cfg
timeout  server  1m
server i-primary_127.0.0.1:1000 127.0.0.1:1000 id 2 cookie i-primary_127.0.0.1:1000 check inter 2s rise 3 fall 2
server default1_localhost:8422 …
```

Thread Safety

---

README.md
lib/synapse/service_watcher/base/base.rb
lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
lib/synapse/service_watcher/multi/resolver/sequential.rb
lib/synapse/service_watcher/multi/resolver/union.rb
lib/synapse/service_watcher/zookeeper/zookeeper.rb
lib/synapse/service_watcher/zookeeper_poll/zookeeper_poll.rb
spec/lib/synapse/multi_resolver/loader_spec.rb
spec/lib/synapse/multi_resolver/sequential_spec.rb
spec/lib/synapse/multi_resolver/union_spec.rb

Adds in two new resolver types:
* `union` which simply merges the results of N watchers
* `sequential` which goes through the watchers in orders and returns the first non-error result
```bash
$ grep "server i-" haproxy.cfg
server i-secondary_127.0.0.2:2000 127.0.0.2:2000 id 2 cookie i-secondary_127.0.0.2:2000 check inter 2s rise 3 fall 2
server i-secondary2_127.0.0.3:2001 127.0.0.3:2001 id 1 cookie i-secondary2_127.0.0.3:2001 check inter 2s rise 3 fall 2
server i-primary_127.0.0.1:1000 127.0.0.1:1000 id 3 cookie i-primary_127.0.0.1:1000 check inter 2s rise 3 fall 2
```
Note that because the ZK watcher will retry until crashing after the limit, the hosts do not change:
```bash
$ grep "server i-" haproxy.cfg
server i-secondary_127.0.0.2:2000 127.0.0.2:2000 id 2 cookie …
```

Add Union & Sequential resolvers

---

lib/synapse.rb
lib/synapse/atomic.rb
lib/synapse/service_watcher/base/base.rb
lib/synapse/service_watcher/multi/multi.rb
lib/synapse/service_watcher/zookeeper_dns/zookeeper_dns.rb
lib/synapse/service_watcher/zookeeper_dns_poll/zookeeper_dns_poll.rb
spec/lib/synapse/service_watcher_ec2tags_spec.rb
spec/lib/synapse/service_watcher_multi_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Adds in the `ZookeeperDnsPollWatcher`, which is a combination of the `ZookeeperPollWatcher` and the `DnsWatcher`.
This is accomplished in part by refactoring the original `ZookeeperDnsWatcher`.
Note: this also contains a slightly unrelated new test: the `skipGc` flag from the cleanup cron job.
```bash
$ RUBYLIB=lib bin/synapse -c ~/test-config/synapse/synapse-dns.json &
$ zookeepercli -servers localhost:2181 -c get /services/service-dns/0001.dns-test
{"host": "google.com", "port": 1000, "name": "i-dns"}
$ grep "server i-" haproxy.cfg
server i-dns_2607:F8B0:4005:805::200E:1000 2607:F8B0:4005:805::200E:1000 id 2 cookie i-dns_2607:F8B0:4005:805::200E:1000 check inter 2s rise 3 fall 2
server i-dns_216.58.194.206:1000 216.58.194.206:1000 id 1 cookie i-dns_216.58.194.206:1000 check inter 2s …
```

Add ZookeeperDnsPollWatcher

---

lib/synapse/service_watcher/zookeeper_dns/zookeeper_dns.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

`ZookeeperDnsWatcher` was not passing the `use_previous_backends` setting to the children watchers, which meant in the children it was using the default value of `true` (even if the original watcher was provided a value of `false`).
I did not touch the other options because I'm not sure what the effect would be of adding _all_ the options in.
@austin-zhu

ZookeeperDnsWatcher: fix use_previous_backends

---

lib/synapse/service_watcher/zookeeper/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Synapse does not specify explicit value for session timeout. By default ruby client uses RECEIVE_TIMEOUT=10000ms which leads to 20-sec session in zk server.
https://github.com/zk-ruby/zookeeper/blob/master/ext/c_zookeeper.rb#L20
The PR sets synapse session timeout to be 36-sec. 
- unit tests: bundle exec rspec
- To verify that zk session is set to 36-sec, manual integration test was executed with zk server: 
- created an instance of client connecting to test zk server. 
- used 4-letter commands to dump connections on zk server: `echo cons | nc localhost 2181 > cons.txt`
- verified the output that connection had 36-sec session with to=36001: 
`/172.18.26.75:53573[1](queued=0,recved=2,sent=2,sid=0x66055392eb24038e,lop=PING,est=1594240596217,to=36001,lcxid=0x0,lzxid=0xffffffffffffffff,lresp=2 …

Set explicit zk session timeout

---

synapse.gemspec

Using `git` within the `gemspec` makes it coupled with the repository being cloned---the "source" of the project itself is no longer sufficient just to build the gem. This also makes it harder to build the gem in CI where the git repository itself may not be present.
Original:
```bash
$ docker run  --rm -it -v `pwd`:/test ruby:2.3.0 bash -c "cd /test && gem build synapse.gemspec && gem install synapse*.gem && rm synapse-*.gem && synapse --help"
...
14 gems installed
Welcome to synapse
Usage: synapse --config /path/to/synapse/config
-c, --config config              path to synapse config
-h, --help                       Display this screen
```
New:
```bash
$ docker run  --rm -it -v `pwd`:/test ruby:2.3.0 bash -c "cd /test && gem build synapse.gemspec && gem install synapse*.gem && rm …
```

Remove usage of git in gemspec

---

lib/synapse/service_watcher/multi/resolver/s3_toggle.rb
lib/synapse/service_watcher/zookeeper/zookeeper.rb
lib/synapse/service_watcher/zookeeper_poll/zookeeper_poll.rb
lib/synapse/version.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Because of the sleep duration (set to 0.5s) in `ZookeeperWatcher` and `ZookeeperPollWatcher`, killing the thread for either will take an average of `0.25s`. Synapse's shutdown sequence will call every watcher's `stop` sequentially.
This means that **for every one of these watchers the Synapse shutdown time increases by ~0.25s**. With one usage of 3000 watchers + another 3000 dual-read watchers, Synapse shutdown can take nearly 25 minutes:
*Note: shutdown starts when thread count starts decreasing, and finishes when thread count increases again (i.e. restarted)*
I removed the `Thread.join` calls which are not really necessary. In Synapse's current design, watchers are only shutdown when the whole process is being shutdown. As such, all the threads are forcefully killed at process exit. …

Do not wait on threads in Zookeeper watchers

---

lib/synapse/service_watcher/dns/dns.rb
lib/synapse/service_watcher/zookeeper_dns/zookeeper_dns.rb
lib/synapse/service_watcher/zookeeper_dns_poll/zookeeper_dns_poll.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Fix a bug in `ZookeeperDnsWatcher` that prevents `frontend` stanzas from being generated in HAProxy. This is a consequence of the fact that this watcher does not expose the `config_for_generator` that is read from Zookeeper.
The fix does the following:
1. Expose `config_for_generator` from `ZookeeperWatcher`
2. Ensure that when the `ZookeeperWatcher`'s `config_for_generator` changes (without a backend change), a notification and re-configuration is triggered
```
$  grep -c frontend /etc/haproxy/haproxy.cfg
1
$ grep frontend /etc/haproxy/haproxy.cfg
$ grep -c frontend /etc/haproxy/haproxy.cfg
10
```
@austin-zhu @Jason-Jian

Properly obtain config_for_generator in ZookeeperDnsWatcher

---

lib/synapse/service_watcher/zookeeper/zookeeper.rb
lib/synapse/service_watcher/zookeeper_poll/zookeeper_poll.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Due to a race condition in the HAProxy config generator, each watcher `start` method should block until there is an initial discover performed. In particular, the watcher needs to have the `config_for_generator` set before it should return from startup.
The race condition occurs due to how the config generator reads the data at [different](https://github.com/airbnb/synapse/blob/5363ac045f13903623c8d40e89f4b85786945e75/lib/synapse/config_generator/haproxy.rb#L933) [times](https://github.com/airbnb/synapse/blob/5363ac045f13903623c8d40e89f4b85786945e75/lib/synapse/config_generator/haproxy.rb#L1007) [for](https://github.com/airbnb/synapse/blob/5363ac045f13903623c8d40e89f4b85786945e75/lib/synapse/config_generator/haproxy.rb#L933) [different](https://github.com/airbnb/synapse/blob/5363ac045f1390 …

Block on watcher start to alleviate HAProxy config generator race condition

---

lib/synapse/service_watcher/zookeeper_dns/zookeeper_dns.rb

Fix race condition when starting up `ZookeeperDnsWatcher`. The race condition is that `@dns` will not exist by the time that `@zk` calls its `reconfigure_callback`, which in turn will call `@dns.backends`.
This was introduced in #333; since the `ZK` watchers will always discover first before completing `start`, they will always call `reconfigure_callback` on startup.
Previously during startup, this error was received when using `ZookeeperDnsWatcher`:
```E, [2020-08-31T09:42:40.828903 #8859] ERROR -- Synapse::Synapse: synapse: encountered unexpected exception #<NoMethodError: undefined method `backends' for nil:NilClass> in main thread```
Now, Synapse starts up properly.
@austin-zhu

Ensure watchers exist in ZookeeperDnsWatcher

---

lib/synapse/service_watcher/base/base.rb
lib/synapse/service_watcher/zookeeper/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/multi_resolver/s3_toggle_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Current ZookeeperWatcher's watch_callback accepts zk event as parameter but ignores it during processing. Every time a zk event is received, watch_callback does all three things regardless of which zk event:
- calling zk.exists on service znode
- calling zk.children on service znode
- calling zk.get on service znode.
But each zk event always contains single change(e.g. child and data event are mutually exclusive) and performing all three calls above are not necessary. For example below are a list of methods supported on zk event:
- node_event? : true for node event and false for session event
- node_child? : true if watched znode children have changed.
- node_chanaged? : true if watched znode data has changed.
- node_created? : true if watched znode was created 
- node_deleted? : true if …

Reduce zk calls with enhanced zk event processing

---

lib/synapse/service_watcher/dns/dns.rb
lib/synapse/version.rb

Add metrics for DNS resolve failure so that it's easier to capture. Also add synapse prefix for legacy logs. 
```
$ bundle exec rspec
Finished in 0.51704 seconds (files took 1.17 seconds to load)
418 examples, 0 failures
```
@panchr

Add metrics for DNS resolve failure. 
