airbnb/synapse

README.md

Reading through the readme is a bit confusing as to which haproxy is which and where file_output actually goes, I've tried fixing that.

Some minor documentation fixups

---

lib/synapse/service_watcher/zookeeper.rb

This is such a bad design, I really dislike that we munge the zk data
multiple times. Unfortunately I don't know a better way to do it yet. I
will work on it.

Adds support to the zookeeper service watcher for haproxy_server_options

---

lib/synapse/service_watcher/zookeeper.rb

Let server_port_override works for zookeeper discovery watcher

Fix zookeeper discovery port override

---

README.md
lib/synapse/service_watcher/zookeeper.rb

This pulls in #148 with some of #104.
@JustinVenus, @benley does this work for both of you?
... we really need some specs for this class

Aurora support

---

Gemfile.lock
lib/synapse/version.rb

bump version to v0.13.0

---

spec/support/minimum.conf.yaml

Fix the spec minimum config to be more realistic

---

README.md

Adding documentation on `label_filter` to Synapse.
to: @jolynch

Add label_filter to README.md

---

Gemfile.lock
lib/synapse/version.rb

Bump synapse version
to: @SonicWang @jolynch

bump version to v0.13.2

---

Gemfile.lock
lib/synapse/version.rb

to: @brianwolfe
i'll push the new version to rubygems after merging

bump version to v0.13.5

---

Gemfile.lock
lib/synapse/version.rb

this version includes the change in #199 to permit managing multiple stats sockets
to: @nwadams

bump version to v0.13.6

---

Gemfile.lock
lib/synapse/version.rb

this version contains only the label-filters refactor with support for specifying multiple labels.
to: @scarletmeow @nwadams @jolynch

bump version to v0.13.7

---

lib/synapse/service_watcher/zookeeper.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Resilient zk watcher

---

lib/synapse/file_output.rb

Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

Minor Fixes

---

README.md
lib/synapse.rb
lib/synapse/config_generator.rb
lib/synapse/config_generator/README.md
lib/synapse/config_generator/base.rb
lib/synapse/config_generator/file_output.rb
lib/synapse/config_generator/haproxy.rb
lib/synapse/service_watcher/README.md
lib/synapse/service_watcher/base.rb
lib/synapse/service_watcher/ec2tag.rb
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/service_watcher/zookeeper_dns.rb
spec/lib/synapse/file_output_spec.rb
spec/lib/synapse/haproxy_spec.rb
spec/lib/synapse/service_watcher_base_spec.rb
spec/lib/synapse/service_watcher_docker_spec.rb
spec/lib/synapse/service_watcher_ec2tags_spec.rb
spec/lib/synapse/service_watcher_marathon_spec.rb
spec/lib/synapse/service_watcher_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb
spec/support/minimum.conf.yaml

Just like we can support multiple service watchers, now we can support
multiple configuration generators which can output in whatever format we
want

Support Pluggable Configuration Generators

---

lib/synapse/config_generator/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

This is to allow us to support domain sockets.

Allow null bind port

---

README.md

https://github.com/jolynch/synapse-nginx

Add docs for nginx config generator

---

lib/synapse/config_generator/haproxy.rb
spec/lib/synapse/haproxy_spec.rb

Merge https://github.com/airbnb/synapse/pull/211

Merge noggi/synapse/haproxy_avoid_noop_reenable_211

---

lib/synapse/haproxy.rb

Currently, on every topology update event Synapse sends re-enable command to HAProxy for every live backend instance, even though that instance may already be `UP`. The number of such backend instances can be quite significant, so after every single topology update Synapse may send thousands of re-enable commands which are essentially noops.
The following changes were made to address the problem:
1. HAProxy command batching: commands are now sent in groups of 4 or less, which reduces
overall number of syscalls per topology update event.
2. Re-enable command is now sent only if a given instance status is not `UP`.
3. Minor performance improvements in HAProxy stats parsing code (~35% time/cpu savings). 
NOTE: command batching in HAproxy was [added in version …

[haproxy] Avoid unnecessary HAProxy re-configuration.

---

lib/synapse.rb

This fixes https://github.com/airbnb/synapse/issues/226.

Support 'service_conf_dir' directive

---

lib/synapse/service_watcher/zookeeper_dns.rb

https://github.com/airbnb/synapse/pull/228 introduced stanza cache in haproxy generator, which relies on the revision counter to detect changes in configuration. This does not work properly with ZookeeperDns watcher which overrides `reconfigure!` method, so changes that happened in its child ZK watcher become invisible to the haproxy generator.
This PR allows for proper propagation of revision updates in ZookeeperDns.
@somic @jolynch @lucaluo @tuckerman @jimmyngo

Propagate revision updates in ZookeeperDns watcher

---

lib/synapse/service_watcher/zookeeper_dns.rb

My previous PR (https://github.com/airbnb/synapse/pull/236) only fixed the ZK 
part of ZK DNS watcher. As the result, only ZK updates were handled correctly.
This change fixes the DNS part as well, so IP address updates will now also
trigger haproxy reconfiguration.
@jimmyngo @tuckerman @jolynch

Bump revision in DNS watcher of ZK DNS

---

config/synapse.conf.json
lib/synapse.rb
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/statsd.rb

This change adds the ability to configure sample rate for individual
metrics exported to datadog.
Reviewers: @lap1817 @ken-experiment

adding sampling settings for statsd metrics

---

Gemfile.lock
lib/synapse/version.rb

Bump up version to 0.16.4

---

lib/synapse/config_generator/base.rb

Add statsd client for config generator - haproxy to emit metrics
@austin-zhu @ken-experiment

Add statsd client for config generator

---

Gemfile.lock
lib/synapse/version.rb

Bump version to 0.16.5

---

Gemfile.lock
lib/synapse/service_watcher/zookeeper.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

https://github.com/airbnb/synapse/pull/290#pullrequestreview-245728706
Followup.
* Add MIN_JITTER and MAX_JITTER
* Add test case.

Add  MIN_JITTER and MAX_JITTER variables

---

.travis.yml

Run tests against Ruby 1.9.3

---

lib/synapse/service_watcher/base/base.rb
lib/synapse/service_watcher/zookeeper_dns/zookeeper_dns.rb
lib/synapse/version.rb
spec/lib/synapse/service_watcher_base_spec.rb
spec/lib/synapse/service_watcher_zookeeper_spec.rb

Perform nil checks for dns watcher config_for_generator
@austin-zhu @gmcatsf

Perform nil checks for dns watcher config_for_generator
